# Generated by Django 4.2 on 2023-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_menuitem_delete_munuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='posting_link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
